on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run generate

      - name: Deploy
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan $HOST > ~/.ssh/known_hosts
          cd .output/public
          tar -cz . | ssh $USER@$HOST "cat > /var/www/tarball.tar.gz"
          ssh $USER@$HOST "cd /var/www && ./update tarball.tar.gz"

      - name: Clean
        if: always()
        run: rm -fr ~/.ssh
