on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run generate

      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.HOST }} > ~/.ssh/known_hosts
          cd .output/public
          tar -cz . | ssh ${{ secrets.USER }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} "cat > /var/www/tarball.tar.gz"
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} "cd /var/www && ./update tarball.tar.gz"

      - name: Clean
        if: always()
        run: rm -fr ~/.ssh
